// <auto-generated />
using System;
using BlunderForge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlunderForge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BlunderForgeDbContext))]
    [Migration("20260713080339_InitialBlunderForge")]
    partial class InitialBlunderForge
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("BlunderForge.Infrastructure.Persistence.Entities.AppSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("BlunderForge.Infrastructure.Persistence.Entities.GameEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentFen")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("InitialFen")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("OpponentElo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerColorChoice")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerSide")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TerminationReason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasFilter("Status = 'Active'");

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("BlunderForge.Infrastructure.Persistence.Entities.GameReviewEntity", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriticalMovesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FutureFocus")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OverallQuality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UsedAi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WentWell")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("GameId");

                    b.ToTable("GameReviews", (string)null);
                });

            modelBuilder.Entity("BlunderForge.Infrastructure.Persistence.Entities.MoveAnalysisEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BestMoveUci")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateMovesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CentipawnLoss")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineSettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EvaluationAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EvaluationBefore")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MoveId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrincipalVariationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MoveId")
                        .IsUnique();

                    b.ToTable("MoveAnalyses", (string)null);
                });

            modelBuilder.Entity("BlunderForge.Infrastructure.Persistence.Entities.MoveEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FenAfter")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("FenBefore")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOpponentMove")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ply")
                        .HasColumnType("INTEGER");

                    b.Property<string>("San")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Uci")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "Ply")
                        .IsUnique();

                    b.ToTable("Moves", (string)null);
                });

            modelBuilder.Entity("BlunderForge.Infrastructure.Persistence.Entities.GameReviewEntity", b =>
                {
                    b.HasOne("BlunderForge.Infrastructure.Persistence.Entities.GameEntity", "Game")
                        .WithOne("Review")
                        .HasForeignKey("BlunderForge.Infrastructure.Persistence.Entities.GameReviewEntity", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("BlunderForge.Infrastructure.Persistence.Entities.MoveAnalysisEntity", b =>
                {
                    b.HasOne("BlunderForge.Infrastructure.Persistence.Entities.MoveEntity", "Move")
                        .WithOne("Analysis")
                        .HasForeignKey("BlunderForge.Infrastructure.Persistence.Entities.MoveAnalysisEntity", "MoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Move");
                });

            modelBuilder.Entity("BlunderForge.Infrastructure.Persistence.Entities.MoveEntity", b =>
                {
                    b.HasOne("BlunderForge.Infrastructure.Persistence.Entities.GameEntity", "Game")
                        .WithMany("Moves")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("BlunderForge.Infrastructure.Persistence.Entities.GameEntity", b =>
                {
                    b.Navigation("Moves");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("BlunderForge.Infrastructure.Persistence.Entities.MoveEntity", b =>
                {
                    b.Navigation("Analysis");
                });
#pragma warning restore 612, 618
        }
    }
}
